/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BotonGenerico: typeof import('./src/components/BotonGenerico.vue')['default']
    CabeceraGenerica: typeof import('./src/components/CabeceraGenerica.vue')['default']
    FormComponent: typeof import('./src/components/FormComponent.vue')['default']
    FormGenerico: typeof import('./src/components/FormGenerico.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputGenerico: typeof import('./src/components/InputGenerico.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectGenerico: typeof import('./src/components/SelectGenerico.vue')['default']
  }
}
