/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/books/': RouteRecordInfo<'/books/', '/books', Record<never, never>, Record<never, never>>,
    '/books/addBook': RouteRecordInfo<'/books/addBook', '/books/addBook', Record<never, never>, Record<never, never>>,
    '/books/editBook': RouteRecordInfo<'/books/editBook', '/books/editBook', Record<never, never>, Record<never, never>>,
    '/books/favoritesBooks': RouteRecordInfo<'/books/favoritesBooks', '/books/favoritesBooks', Record<never, never>, Record<never, never>>,
    '/books/readBooks': RouteRecordInfo<'/books/readBooks', '/books/readBooks', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/logout': RouteRecordInfo<'/logout', '/logout', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
  }
}
