name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # Build job
  build:
    # Especificar runner y construir las aplicaciones
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Construir aplicación Angular
      - name: Build Angular
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          cd angular
          npm install
          npm run build.ghPages
      - run: |
          mkdir -p dist/angular
          cp -r angular/dist/angular/browser/* dist/angular

      # Construir aplicación React
      - name: Build React
        run: |
          cd react
          npm install
          npm run build.ghPages
      - run: |
          mkdir -p dist/react
          cp -r react/build/* dist/react

      # Construir aplicación Vue
      - name: Build Vue
        run: |
          cd vue
          npm install
          npm run build
      - run: |
          mkdir -p dist/vue
          cp -r vue/dist/* dist/vue

      # Copiar archivo index.html en la raíz
      - run: |
          cp index.html dist/

      # Subir archivos estáticos como artefactos
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # para desplegar en Pages
      id-token: write   # para verificar que el despliegue es válido
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4