name: Build and deploy

on:
  push:
    branches: [ "main" ]

jobs:
  # Build job
  build:
    # Specify runner + build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: actions/setup-node@v4
        with:
          node-version: 22
          # cache: 'npm'

      # Build Angular
      - run: |
          cd angular
          npm install
          npm run build.ghPages

      # Build React
      - run: |
          cd react
          npm install
          npm run build.ghPages

      # Build Vue
      - run: |
          cd vue
          npm install
          npm run build.ghPages

      # Copy Angular build
      - run: |
          mkdir -p dist/angular
          cp -r angular/dist/angular/browser/* dist/angular

      # Copy React build
      - run: |
          mkdir -p dist/react
          cp -r react/dist/* dist/react

      # Copy Vue build
      - run: |
          mkdir -p dist/vue
          cp -r vue/dist/* dist/vue

      # Copy index.html
      - run: |
          cp index.html dist/

      # Upload static files as artifact
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: dist/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4